# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d63795b18383bbb6a9c746f28913a79c"
name = "discounterY"
handle = "discountery"
application_url = "https://compatible-her-presentation-ld.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "thockthockstore.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts,write_products"

[auth]
redirect_urls = [
  "https://compatible-her-presentation-ld.trycloudflare.com/auth/callback",
  "https://compatible-her-presentation-ld.trycloudflare.com/auth/shopify/callback",
  "https://compatible-her-presentation-ld.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
