# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "44b9fa6ca1377f5079b7860180dbae1c"
name = "MD Dev A"
handle = "md-dev-a"
application_url = "https://editing-clarity-nec-nasdaq.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "md-dev-a.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts,write_products"

[auth]
redirect_urls = [
  "https://editing-clarity-nec-nasdaq.trycloudflare.com/auth/callback",
  "https://editing-clarity-nec-nasdaq.trycloudflare.com/auth/shopify/callback",
  "https://editing-clarity-nec-nasdaq.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
