# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b3fd28c598851912e5da46b0017abb6a"
name = "Metafield Discounts"
handle = "metafield-discounts"
application_url = "https://tank-mounting-implications-aerospace.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "thockthockstore.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts,write_products"

[auth]
redirect_urls = [
  "https://tank-mounting-implications-aerospace.trycloudflare.com/auth/callback",
  "https://tank-mounting-implications-aerospace.trycloudflare.com/auth/shopify/callback",
  "https://tank-mounting-implications-aerospace.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
